version: 0.1

phases:
  build:
    commands:
      - echo Nothing to do yet
artifacts:
  files:
    - index.html
    - favicon.ico
    - Rashi-Resume.pdf
    - manifest.json
    - asset-manifest.json
    - ./*.png
    - static/css/*.css
    - static/js/*.js
    - static/media/*
